// Mocks generated by Mockito 5.4.4 from annotations
// in approach_to_charge/test/infrastructure/provider/home_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:approach_to_charge/application/usecases/call_catlist_usecase.dart'
    as _i2;
import 'package:approach_to_charge/application/usecases/error/get_list_cat_error.dart'
    as _i5;
import 'package:approach_to_charge/application/usecases/error/search_cat_error.dart'
    as _i8;
import 'package:approach_to_charge/domain/entity/cat.dart' as _i6;
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CallCatListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallCatListUseCase extends _i1.Mock
    implements _i2.CallCatListUseCase {
  MockCallCatListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.GetListCatError, List<_i6.Cat>>> getListCat({
    int? limit = 10,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListCat,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.GetListCatError, List<_i6.Cat>>>.value(
                _i7.dummyValue<_i4.Either<_i5.GetListCatError, List<_i6.Cat>>>(
          this,
          Invocation.method(
            #getListCat,
            [],
            {
              #limit: limit,
              #page: page,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.GetListCatError, List<_i6.Cat>>>);

  @override
  _i4.Either<_i8.SearchCatError, List<_i6.Cat>> searchCat({
    required String? breed_name,
    required List<_i6.Cat>? origincats,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCat,
          [],
          {
            #breed_name: breed_name,
            #origincats: origincats,
          },
        ),
        returnValue:
            _i7.dummyValue<_i4.Either<_i8.SearchCatError, List<_i6.Cat>>>(
          this,
          Invocation.method(
            #searchCat,
            [],
            {
              #breed_name: breed_name,
              #origincats: origincats,
            },
          ),
        ),
      ) as _i4.Either<_i8.SearchCatError, List<_i6.Cat>>);
}
